### ISSUE TITLE
Enhancement: high dpi support

### ISSUE THREAD

**Issue by cyn0x8** [FunkinCrew/Funkin#2568]
## What is your suggestion, and why should it be implemented?

support for dpi scaling:

currently the game window resolution does not match the actual window size if the display dpi is scaled beyond 100%, which leads to slightly blurry and/or pixelated visuals

you guys could probably follow the [CNE](https://github.com/FNF-CNE-Devs/CodenameEngine) implementation for this

**Comment by AbnormalPoof** [comment]
#3522 implements this.

**Comment by EliteMasterEric** [comment]
#3522 got closed as redundant so looks like this is resolved.

**Comment by lunacynne** [comment]
still doesnt seem to be implemented for windows as of latest develop
tried both `debug` and `final` builds

<img width="1977" height="1171" alt="Image" src="https://github.com/user-attachments/assets/92ec9ad5-2fa2-46e7-9216-f1b6b4395b85" />

<img width="1954" height="1164" alt="Image" src="https://github.com/user-attachments/assets/48a5b0c3-4cd5-4ee3-b04c-dd1075b4e3ba" />
