### ISSUE TITLE
Bug Report: Note Pressing Keybinds Override Eachother When Bound, Preventing Multiple Keybinds

### ISSUE THREAD

**Issue by Average-FNF-Modder** [FunkinCrew/Funkin#2780]
## Describe the bug

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;When changing the 2 keybinds sets for game play, upon entering a song, one of the 2 sets will take over the other and the over written one will not be functional. Upon exiting said song and going back to settings, both keybind sets will read the same bindings. This makes it impossible to have to keybinds for each key as intended.

## To Reproduce

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Go into settings, change you note hit keybinds, enter a song, one set of keys will not work. You can exit the song and then also see the bug in settings with the keybinds.
## Expected behavior
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;It should let me have to keybinds per note. I only end up getting one binding. Very sad.

## Screenshots/Video
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;It's not really need here. You get the idea. Both keybind slots say the same thing, the end.

## Desktop
 - OS: It happens on the Windows 10 version.
 
 - Browser: I know it happens on Microsoft Edge.
 
 - Version: At LEAST up to 0.4.0, might also be in 0.4.1, didn't see it in the patch fixes.

**Comment by Hundrec** [comment]
I tested both sets of arrow inputs in a song on 0.5.1 and it worked fine.
I think this is resolved!

**Comment by Average-FNF-Modder** [comment]
> I tested both sets of arrow inputs in a song on 0.5.1 and it worked fine. I think this is resolved!

I just tested it myself once again, and the bug still occurred for me; maybe the bug varies by device, but it's definitely still present.

**Comment by Hundrec** [comment]
Can you provide a video? I'm really curious to know more about this issue

**Comment by Average-FNF-Modder** [comment]
Sure thing bro. 

https://github.com/user-attachments/assets/bd0da08c-09b4-4f96-a279-6f36531276f5

I try to go play Pico 2-handed, one side doesn't work, and I'm fucked. It's annoying for me especially cause I like to switch between one handed arrow keys only and 2 handed a s up right.

**Comment by Hundrec** [comment]
So if you try to bind WASD to either the first or the second column, it resets into the arrow keys?

**Comment by Average-FNF-Modder** [comment]
> So if you try to bind WASD to either the first or the second column, it resets into the arrow keys?

It's happened the other way around as well. I haven't tested enough to see if there is something specific that decides which side will override the other.

**Comment by Hundrec** [comment]
That's really strange. I thought arrow keys and WASD were bound as the default pair of controls

**Comment by Average-FNF-Modder** [comment]
> That's really strange. I thought arrow keys and WASD were bound as the default pair of controls

They actually are, and work fine that way. Something interesting about the bug is that it doesn't happen until you mess with the keybinds once to start. If you never change them, you'll get arrow keys and wasd working as intended. But as soon as you touch them once, like when I changed to dfjk one time, the bug starts, and then will keep happening forever onwards.

**Comment by Lasercar** [comment]
Is anyone else able to reproduce this issue?

**Comment by Lasercar** [comment]
Can you still reproduce this in 0.6.3?

**Comment by Average-FNF-Modder** [comment]
Nope! It seems to be all fixed
