### ISSUE TITLE
Bug Report: Normal Game Over screen plays in one of Week 6's songs

### ISSUE THREAD

**Issue by lauyc-c** [FunkinCrew/Funkin#311]
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

### Web
- [x] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [x] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [x] Windows x86_64
- [ ] Linux
- [ ] macOS

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Getting a Game Over on the song "Thorns" in Week 6.
## Please describe your issue. Provide extensive detail and images if possible.
Whenever I got a Game Over in said song, the normal game over animation and music would play instead of the pixelated version.

**Comment by Tiago-QBois** [comment]
Happens on actually every Browser and Platform (NG, Itch.io)

**Comment by ActualMandM** [comment]
This issue is already fixed in the source code: b966129233d6ec7a09bc91f79616451ceb7d91b6

**Comment by StreamyGuy** [comment]
Hmm... it's still happening for me. Do I have to download Haxe or something?
