### ISSUE TITLE
Unknown issue is causing gamplay to skip, or desync with the song, resulting in gameplay stutter, lag, etc

### ISSUE THREAD

**Issue by TudioS20** [FunkinCrew/Funkin#3495]
### Issue Checklist

- [ ] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.1

### Context (Provide images, videos, etc.)

Upon loading any given song, sometimes the game's audio will stutter, or lag. When this occurs, the general gameplay + visuals will stutter as well.

I have a somewhat low-end computer, so bugs will happen to me that aren't actually bugs, but from what I've heard elsewhere, this bug has happened before to others.

### Steps to reproduce (or crash logs, errors, etc.)

Just...play a song and see what happens. It's kinda random, so I don't know if it happens with EVERYONE.

**Comment by biomseed** [comment]
This happens to me too. It's a bug that happened in the latest patch. I think it happens to everyone

**Comment by Hundrec** [comment]
Can you provide a video of this happening?

**Comment by TudioS20** [comment]
Sadly, no, I can't. However, I CAN tell you that it has been reported on Twitter. Multiple people have talked about lag spikes and things similar to it.

If you check Ninjamuffin's Twitter, he made a post where he talked about 0.5.1 being released. There's some replies that talk about it.

**Comment by Hundrec** [comment]
Thanks for the info!
This tweet demonstrates the bug quite well: https://x.com/MajidyMajidy_/status/1840811401683636307

**Comment by TudioS20** [comment]
What I saw wasn't as...harsh. It was somewhat more...subtle, but yes, that IS in fact, the bug.

**Comment by NotHyper-474** [comment]
Apparently it's the input offset causing this. Another video demonstrating the issue:

https://github.com/user-attachments/assets/79468dd8-5e68-44ea-9555-333de758c4f4

**Comment by TudioS20** [comment]
Yeah, that's the bug. But my offsets aren't changed. I don't even know HOW to change it.

What I had was VERY mild, only appearing like, a couple times. It wasn't...THIS bad.

**Comment by biomseed** [comment]
> Apparently it's the input offset causing this. Another video demonstrating the issue:
> 
>  8mb.video-dWi-yFMMw8Ns.mp4

It is NOT the input offset. I have not changed it once in my entire life

**Comment by NotHyper-474** [comment]
> It is NOT the input offset. I have not changed it once in my entire life

Well, I could only replicate it with a different offset. Also I wasn't 100% sure hence the "apparently"

**Comment by biomseed** [comment]
> Well, I could only replicate it with a different offset. Also I wasn't 100% sure hence the "apparently"

Don't worry, I knew you weren't sure

**Comment by biomseed** [comment]
@NotHyper-474 limiting your fps may actually cause the bug. I changed it to my monitor's, 75 (I'm normal). Try a different fps limit or just 75

**Comment by NotHyper-474** [comment]
Testing with 30 FPS I've noticed some stutters but nothing like the other video. Can be noticed at 0:03 and 0:13

https://github.com/user-attachments/assets/7841ec80-9e9a-42b1-b9cd-9aae5f4c5e6d

**Comment by TudioS20** [comment]
That's the amount of stutter I have. It's VERY subtle, usually...

I wonder if I should cap the game at 30 FPS too...?

**Comment by SEBBY180** [comment]
I tried increasing the FPS, and it helps a bit, but it doesn't get rid of the audio stutter.

**Comment by SEBBY180** [comment]
The more notes are on screen, the more the audio stutters, it seems.

**Comment by TudioS20** [comment]
Well, regardless, this actually seems to be an issue, and I PRAY TO GOD ALMIGHTY the Funkin' devs see this issue, and fix it ASAP, because...I REALLY don't wanna start work on my mod with...THAT interfering with it, among other issues.

**Comment by Squiddu** [comment]
I've been recording all the issues I've had with offset since 0.4.x, and my god it just keeps getting worse.. obviously whether or not this specifically has anything to do with offset is still undecided, but it's still a possibility, given the weird minor visual/audio stutters I noticed ever since 0.4.x (where offset seemed to generally at least.. not crash anywhere).

**Comment by Johnsen290** [comment]
same thing for me, I changed the visual offsets to default 0, did not fix it, working better before the patch

**Comment by biomseed** [comment]
Why did you change the title to that Eric? That's not the issue

**Comment by AbnormalPoof** [comment]
I’m pretty sure it’s because the input offsets are the source of the issue.

**Comment by biomseed** [comment]
> I’m pretty sure it’s because the input offsets are the source of the issue.
> 
> Had the same problem when porting over a few charts of mine, but setting the input offset to 0 fixed it.
> 
> It’s probably a resync issue (The tolerance is REALLY low now. Kade set the tolerance to 5 ms in another PR compared to the previous 100 ms)

I did not change my input offsets at all and I still have the issue

**Comment by Hundrec** [comment]
Looks to me like the resync feature is interacting with anything that offsets the song, including input offsets and lag. 
biomseed, are you experiencing performance issues/running on a lower end device?

**Comment by biomseed** [comment]
> Looks to me like the resync feature is interacting with anything that offsets the song, including input offsets and lag. biomseed, are you experiencing performance issues/running on a lower end device?

I am not on a low end device. It has run the game completely fine before the patch at the full fps limit (168)

**Comment by Hundrec** [comment]
Right after I asked you that, I encountered this bug while trying to play Ugh Erect on my decent PC ...with 0ms input offset.

I have no idea what's causing this, but I suggest that this issue be renamed to include "anything that desyncs the song"


https://github.com/user-attachments/assets/393e219e-feab-4271-9e02-1facac4f3a6e

**Comment by biomseed** [comment]
Which FPS limit are you using? Is it 60?

**Comment by Hundrec** [comment]
Yes, I'm on 60fps
I'll try again with my monitor's 75fps

**Comment by AbnormalPoof** [comment]
> The tolerance is REALLY low now.

^ I’m not sure if offsets are the culprit here, but it might be resync for sure.

**Comment by biomseed** [comment]
> Edit 2: It only seems to be happening on Ugh Erect / Ugh Hard. High Erect and Cocoa Erect don't stutter at all. This makes me believe the song is being desynced by something causing lag spikes in Week 7
Ugh Erect is having a lot more stutters for me, though it might just be placebo.

**Comment by TudioS20** [comment]
Okay, I'm back.

So, my issue tends to occur...really...anywhere, with any song. My input offsets are at default, and I've played with different FPS.

The issue is not entirely input offsets. It COULD be, and there is a STRONG possibility that it COULD be, but my offsets are at zero, default, unchanged since the earliest versions, and I DID NOT have this issue prior to 0.5.1.



As for EliteMasterEric changing the name, I do not believe this is 100% tethered to input offsets AT ALL. 

I don't think we really know 100% WHAT is causing this in general, so with all the respect I can give, I am just letting you know: I am going to change the name to something more neutral, or something that highlights the issue in a more...yea, neutral way, because I do not believe the issue has a definitive answer yet.

**Comment by Johnsen290** [comment]
> Okay, I'm back.
> 
> So, my issue tends to occur...really...anywhere, with any song. My input offsets are at default, and I've played with different FPS.
> 
> The issue is not entirely input offsets. It COULD be, and there is a STRONG possibility that it COULD be, but my offsets are at zero, default, unchanged since the earliest versions, and I DID NOT have this issue prior to 0.5.1.
> 
> As for EliteMasterEric changing the name, I do not believe this is 100% tethered to input offsets AT ALL.
> 
> I don't think we really know 100% WHAT is causing this in general, so with all the respect I can give, I am just letting you know: I am going to change the name to something more neutral, or something that highlights the issue in a more...yea, neutral way, because I do not believe the issue has a definitive answer yet.

could be because of how they "fixed" the offset system, they're supposed to fix songs becoming swing rhythm if you have a very high visual offset, and prevent that

**Comment by oddMLan** [comment]
Can confirm this issue, also confirm raising the FPS limit helps a bit, with 60 fps cap is really bad, but with 120 fps cap it's still there but not as bad. But I never had this issue with version 0.5.0, so this is also a regression. Nothing a quick `git bisect` can't help with :)

**Comment by AbnormalPoof** [comment]
Ohhh noo...
![Screenshot 2024-10-02 at 9 15 14 AM](https://github.com/user-attachments/assets/07035a28-d765-42d8-bc6a-588cfe9f7bbe)

### Explanation
My input offsets are at 150 ms.
Using this line as an example (from Tutorial):
```
source/funkin/play/PlayState.hx:1464: VOCALS NEED RESYNC
source/funkin/play/PlayState.hx:1465: 150
source/funkin/play/PlayState.hx:1466: 456
source/funkin/play/PlayState.hx:1467: 306
source/funkin/play/PlayState.hx:2101: Resyncing vocals to 306
```
`456` is the current `FlxG.sound.music.time`. `306` is `correctSync`, which is this: `Math.min(FlxG.sound.music.length, Math.max(0, Conductor.instance.songPosition - Conductor.instance.combinedOffset));`

`150` is the deviation in ms. Basically meaning how much it desyncs in milliseconds.

### The issue
```haxe
if (!startingSong && (Math.abs(FlxG.sound.music.time - correctSync) > 5 || Math.abs(vocals.checkSyncError(correctSync)) > 5))
```
This is the line causing the issue.
It checks if the deviation is ***over*** 5ms, if it is, then it resyncs the vocals.
And since `150` is the deviation... yeah...

**Comment by Burgerballs** [comment]
I'll probably make a PR for this lol

**Comment by TudioS20** [comment]
Wait, so we actually found the issue!?

**Comment by JustKolosaki** [comment]
Surprisingly changing line 416 in `Conductor` to this fixes it:
![image](https://github.com/user-attachments/assets/955f8f21-f8cd-4778-94c0-7f794ab3d980)

Footage (my current offset settings are 150ms):
https://github.com/user-attachments/assets/f66ac4dd-d88b-45fb-91c7-343ae70b1ae4

**Comment by CRLurker** [comment]
So what can I do to stop the issue? Like my version is so bad the song won't even play.

**Comment by AbnormalPoof** [comment]
Either compile the `develop` branch or wait for v0.5.2.

**Comment by AbnormalPoof** [comment]
Fixed in v0.5.2.

**Comment by SEBBY180** [comment]
This issue is still in 0.5.2 unless you set the framerate to at least 125.

**Comment by JustKolosaki** [comment]
It's on me for not testing my hypothetical solution (that was accepted n merged n stuff) for a higher range of framerates, I apologize,,,,,

**Comment by EliteMasterEric** [comment]
It's definitely fixed now.

**Comment by biomseed** [comment]
> It's definitely fixed now.

It's definitely not as some people are still having the issue

**Comment by oddMLan** [comment]
> It's definitely fixed now.

Famous last words

**Comment by amyspark-ng** [comment]
the issue DEFINETELY still exists

**Comment by Hundrec** [comment]
It's okay Eric
We're always here to hunt down bugs for you and make sure they're totally fixed!

**Comment by NotHyper-474** [comment]
Uhh...

https://github.com/user-attachments/assets/f280fdf7-0ecf-46ea-b3a4-f636884c1da7

Doesn't happen on Windows (although the stutters are still there), might be because I'm on WSL so in here the subtle stutters become way less subtle...

**Comment by Hundrec** [comment]
Another great remix bug, almost as good as Swing Mode

**Comment by Johnsen290** [comment]
holy crap, that's really terrible

**Comment by ThatGreenBlur** [comment]
can we reopen this issue? its still a massive issue with mid-end hardware and makes weeks like week 5 on nightmare difficulty practically impossible, this song resyncing buffer literally is so bad it desyncs more after a resync to the point that the entire resyncing process should just be removed instead, i have to spam pause everytime its gonna be bf's turn so i do the resync myself

**Comment by ThatGreenBlur** [comment]
ideally a system like this shouldn't even interrupt gameplay at all and should most likely be only a audio side system instead, i have to go back to v0.5.0 to avoid this issue entirely 

https://github.com/user-attachments/assets/735f24ff-b398-42ad-8acb-47c96ec06904
