### ISSUE TITLE
Bug Report: Strange behaviour of freeplay section animation

### ISSUE THREAD

**Issue by Dorentix** [FunkinCrew/Funkin#4037]
### Issue Checklist

- [x] I have properly named my issue
- [x] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.3

### Description (include any images, videos, errors, or crash logs)

https://github.com/user-attachments/assets/f3508b70-4e93-41cc-994b-ea05bb66096b

**Comment by Hundrec** [comment]
Can you describe what is happening here? It looks to me like the animation stutters a little, but nothing disruptive.

**Comment by Dorentix** [comment]
> Can you describe what is happening here? It looks to me like the animation stutters a little, but nothing disruptive.

sometimes it has a floating animation, and sometimes it doesn't, and after you spam it starts to float in turns

**Comment by trayfellow** [comment]
Ok yeah this is something i've seen and wondered about before, the sorting letters should always have a looping floating up to down animation, but sometimes the behavior is inconsistent and it doesnt loop the animation or just outright doesnt play it

**Comment by Hundrec** [comment]
Gotcha, nice catch!

**Comment by Dorentix** [comment]
this is fixed now

**Comment by Lasercar** [comment]
Yeah, this is partially fixed, the animation restarts after finishing now, but it doesn't restart it when it's selected again.

**Comment by Dorentix** [comment]
> Yeah, this is partially fixed, the animation restarts after finishing now, but it doesn't restart it when it's selected again.

for me it's always looped, even if i select it again

**Comment by Lasercar** [comment]
> > Yeah, this is partially fixed, the animation restarts after finishing now, but it doesn't restart it when it's selected again.
> 
> for me it's always looped, even if i select it again

If you pay attention to the direction it moves, you'd notice that it doesn't restart it, but instead just continues the animation from where it left off.

You can easily test this by changing between two letters - they should always move up when you switch to them.
