### ISSUE TITLE
Bug Report: Darnell Pixel Icon - Stray Pixel

### ISSUE THREAD

**Issue by Tureen64** [FunkinCrew/Funkin#4301]
### Issue Checklist

- [x] I have read the [Contributing Guide](https://github.com/FunkinCrew/Funkin/blob/main/docs/CONTRIBUTING.md)
- [x] I have checked the Issues/Discussions pages to see if my issue has already been reported
- [x] I have properly titled my issue

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

During selection on any of the Darnell songs, when the animation from the animated icon plays, Darnell has a stray pixel on the top left of his icon
![Image](https://github.com/user-attachments/assets/a58cc32a-ce28-49fb-9e43-f019a6aa4076)

**Comment by AbnormalPoof** [comment]
Literally unplayable.

**Comment by JackXson-Real** [comment]
Why are you still on 0.5.1

**Comment by charlesisfeline** [comment]
> Why are you still on 0.5.1

idk but, tbf some people may prefer different versions so its not that big of a deal really

**Comment by JackXson-Real** [comment]
> > Why are you still on 0.5.1
> 
> idk but, tbf some people may prefer different versions so its not that big of a deal really

If you’re reporting a bug, you need to be using the latest available version since there’s a good chance the bug is fixed in a later version. In this case you did get lucky since this is still in 0.5.3, but keep in mind if you are going to report bugs, or just make issues in general, you need to be in the latest version to avoid creating duplicate issues.

**Comment by charlesisfeline** [comment]
> If you’re reporting a bug, you need to be using the latest available version since there’s a good chance the bug is fixed in a later version. In this case you did get lucky since this is still in 0.5.3, but keep in mind if you are going to report bugs, or just make issues in general, you need to be in the latest version to avoid creating an issue on something that is already fixed.

fair enough

**Comment by charlesisfeline** [comment]
however, this issue still occurs in 0.5.3 so...

![Image](https://github.com/user-attachments/assets/eb950e22-d8e2-4f10-bddd-e629cd77361c)

**Comment by Average-FNF-Modder** [comment]
This needs to be marked as high priority in the same vein as the 2hot capitalization inconsistency. This shit is literally unplayable, I'm cancelling the game right now.

**Comment by Hundrec** [comment]
Already is!

![Image](https://github.com/user-attachments/assets/f743b63b-cbde-42fb-ad90-f7fe23dd9970)

**Comment by Average-FNF-Modder** [comment]
> Already is!
> 
> ![Image](https://github.com/user-attachments/assets/f743b63b-cbde-42fb-ad90-f7fe23dd9970)

Woopsies. As it should be!
