### ISSUE TITLE
Bug Report: Chart Editor displays notekind tooltips incorrectly

### ISSUE THREAD

**Issue by aquilacrash** [FunkinCrew/Funkin#5929]
### Issue Checklist

- [X] I have read the [Contributing Guide](<https://github.com/FunkinCrew/Funkin/blob/main/docs/CONTRIBUTING.md>)
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported
- [X] I have properly titled my issue
- [X] I did not have any mods installed when I encountered this issue

### Platform

Windows (Downloadable Build)

### Browser

None

### Mobile Device Model

*No response*

### Mobile OS Version

*No response*

### Version

0.7.4

### Description (include any images, videos, errors, or crash logs)

<img src="https://uploads.linear.app/b9f0050d-7020-42ad-9d4b-7551ff30d00f/5208fd8d-e4d1-4d6c-9b7e-b483873903ad/a30c11a4-e458-4a8a-970b-d8adbd79a41a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2I5ZjAwNTBkLTcwMjAtNDJhZC05ZDRiLTc1NTFmZjMwZDAwZi81MjA4ZmQ4ZC1lNGQxLTRkNmMtOWI3ZS1iNDgzODczOTAzYWQvYTMwYzExYTQtZTQ1OC00YThhLTk3MGItZDhhZGJkNzlhNDFhIiwiaWF0IjoxNzcxOTcyMDc4LCJleHAiOjE4MDM1NDI2Mzh9.XucHTQ610oTasi6xDyv-NfurdMzlBipUsuQXbELFDyw " alt="Image" width="2560" data-linear-height="1440" />

When I change chart from Blazin' to another song this shows up<br>(As you can see I didnt put the weekend-1-block-high note)

### Steps to Reproduce

1. Open the game
2. Go to Chart Editor
3. Open Blazin' (Pico mix of course)
4. Close Chart Editor
5. Go to Chart Editor again
6. Load a random song (not Blazin')
7. Put the cursor on random squares of the chart (on each one wait 5 seconds) and it will show

**Comment by Hundrec** [comment]
I've also noticed the tooltips and indicators can be a bit finnicky, so we should iron it out

**Comment by EliteMasterEric** [comment]
This got fixed in v0.8.2 by #6929 (wow exactly 1,000 issues later)

**Comment by Hundrec** [comment]
Tooltips are still very inconsistent and linger around, so I'd say this isn't fixed yet.
